FROM ghcr.io/eastata/zeth:base-latest

LABEL org.opencontainers.image.source https://github.com/eastata/zeth

COPY . /home/zeth

RUN cd /home/zeth && git submodule update --init --recursive

WORKDIR /home/zeth

CMD ["/bin/bash"]
